apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - namespace.yaml
  - app.yaml

components:
  - ../../../_components/cert-issuer
  - ../../../_components/certificate
  - ../../../_components/op-eso-integration

patches:
  - target:
      version: v1
      group: cert-manager.io
      kind: Certificate
      name: czifro-cloud-cert
    patch: |-
      - op: replace
        path: /metadata/name
        value: whoami-czifro-cloud-cert
      - op: replace
        path: /spec/secretName
        value: whoami-czifro-cloud-cert
      - op: replace
        path: /spec/dnsNames
        value:
          - whoami.czifro.cloud
  - target:
      version: v1
      group: external-secrets.io
      kind: SecretStore
      name: 1password-sdk-backend
    patch: |-
      - op: replace
        path: /metadata/name
        value: whoami-1password-sdk-backend
      - op: replace
        path: /spec/secretName
        value: whoami-1password-sdk-backend
      - op: replace
        path: /spec/provider/onepasswordSDK/vault
        value: czifro-cloud-prod


